// Curated prompt marketplace catalog.
// Each pack contains prompts that import directly into prompt_templates.
// Adding a new source = add a new entry to MARKETPLACE_PACKS.

export type PromptCategory = 'discovery' | 'category' | 'occasions' | 'problemSolution' | 'trust' | 'geographic'
export type SupportedLang = 'nl' | 'en'

export interface MarketplacePrompt {
  id: string
  title: string
  description: string
  template: string            // raw template with {location}, {businessType}, {subtype} placeholders
  category: PromptCategory
  language: SupportedLang
  tags: string[]
  estimatedTokens: number
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  useCases: string[]
}

export interface MarketplacePack {
  id: string
  name: string
  nameNl: string
  description: string
  descriptionNl: string
  category: string            // display category for filtering
  tags: string[]
  prompts: MarketplacePrompt[]
  author: string
  version: string
}

export const MARKETPLACE_PACKS: MarketplacePack[] = [
  // ── Restaurant AI Visibility Pack ──────────────────────────────────────────
  {
    id: 'restaurant-ai-visibility',
    name: 'Restaurant AI Visibility Pack',
    nameNl: 'Restaurant AI-zichtbaarheidspakket',
    description: 'Core prompts for measuring how AI models discover and recommend restaurants. Covers the full audit spectrum across ChatGPT, Claude, Gemini and Perplexity.',
    descriptionNl: 'Kernprompts voor het meten hoe AI-modellen restaurants ontdekken en aanbevelen. Dekt het volledige auditspectrum over ChatGPT, Claude, Gemini en Perplexity.',
    category: 'AI Visibility',
    tags: ['ai', 'visibility', 'discovery', 'restaurant', 'core'],
    author: 'Finded',
    version: '1.0',
    prompts: [
      {
        id: 'aiv-001',
        title: 'General restaurant discovery',
        description: 'Ask AI which restaurants it recommends in a city — the most universal visibility signal.',
        template: 'What are the best {businessType}s in {location}?',
        category: 'discovery',
        language: 'en',
        tags: ['discovery', 'general'],
        estimatedTokens: 12,
        difficulty: 'beginner',
        useCases: ['Baseline visibility check', 'City-level ranking'],
      },
      {
        id: 'aiv-002',
        title: 'Cuisine-specific recommendation',
        description: 'Targets cuisine-type searches — high intent, frequently asked.',
        template: 'Which {subtype} restaurants do you recommend in {location}?',
        category: 'category',
        language: 'en',
        tags: ['cuisine', 'category', 'recommendation'],
        estimatedTokens: 14,
        difficulty: 'beginner',
        useCases: ['Cuisine visibility', 'Category ranking'],
      },
      {
        id: 'aiv-003',
        title: 'Occasion-based dining',
        description: 'Occasion prompts capture high-value reservation intent (date nights, birthdays, business dinners).',
        template: 'Where should I take my partner for a romantic dinner in {location}?',
        category: 'occasions',
        language: 'en',
        tags: ['occasion', 'romantic', 'date-night'],
        estimatedTokens: 18,
        difficulty: 'beginner',
        useCases: ['Occasion visibility', 'High-value reservations'],
      },
      {
        id: 'aiv-004',
        title: 'Problem-solution dining',
        description: 'Captures searches where diners describe a specific situation or constraint.',
        template: 'I need a {businessType} in {location} that works for groups of 10 or more. What do you suggest?',
        category: 'problemSolution',
        language: 'en',
        tags: ['group', 'problem-solution', 'constraint'],
        estimatedTokens: 22,
        difficulty: 'intermediate',
        useCases: ['Group dining visibility', 'Constraint-based search'],
      },
      {
        id: 'aiv-005',
        title: 'Trust and reputation',
        description: 'Tests whether AI associates the restaurant with quality signals like awards, reviews and reputation.',
        template: 'Which {subtype} restaurants in {location} are most highly rated and trusted?',
        category: 'trust',
        language: 'en',
        tags: ['trust', 'reputation', 'ratings'],
        estimatedTokens: 16,
        difficulty: 'beginner',
        useCases: ['Reputation audit', 'Trust signal testing'],
      },
      {
        id: 'aiv-006',
        title: 'Neighbourhood discovery',
        description: 'Geographic prompts that test hyper-local visibility within a city district.',
        template: 'What are the best places to eat near {location}?',
        category: 'geographic',
        language: 'en',
        tags: ['geographic', 'neighbourhood', 'local'],
        estimatedTokens: 13,
        difficulty: 'beginner',
        useCases: ['Local visibility', 'Neighbourhood SEO'],
      },
      // Dutch variants
      {
        id: 'aiv-nl-001',
        title: 'Algemene restaurantontdekking',
        description: 'Basisvraag: welke restaurants beveelt AI aan in een stad?',
        template: 'Wat zijn de beste {businessType}s in {location}?',
        category: 'discovery',
        language: 'nl',
        tags: ['discovery', 'algemeen'],
        estimatedTokens: 12,
        difficulty: 'beginner',
        useCases: ['Basischeck zichtbaarheid', 'Stadsranking'],
      },
      {
        id: 'aiv-nl-002',
        title: 'Keuken-specifieke aanbeveling',
        description: 'Richt zich op zoekopdrachten per keukenstijl — hoge intentie, vaak gesteld.',
        template: 'Welke {subtype} restaurants raad je aan in {location}?',
        category: 'category',
        language: 'nl',
        tags: ['keuken', 'categorie', 'aanbeveling'],
        estimatedTokens: 14,
        difficulty: 'beginner',
        useCases: ['Keukenzichtbaarheid', 'Categorieranking'],
      },
      {
        id: 'aiv-nl-003',
        title: 'Gelegenheidsgedreven diner',
        description: 'Legt waardevolle reserveringsintentie vast (romantisch diner, verjaardag, zakelijk).',
        template: 'Waar kan ik mijn partner mee naartoe nemen voor een romantisch diner in {location}?',
        category: 'occasions',
        language: 'nl',
        tags: ['gelegenheid', 'romantisch', 'date-night'],
        estimatedTokens: 20,
        difficulty: 'beginner',
        useCases: ['Gelegenheidszichtbaarheid', 'Hoogwaardige reserveringen'],
      },
    ],
  },

  // ── Local SEO Pack ──────────────────────────────────────────────────────────
  {
    id: 'local-seo',
    name: 'Local SEO Pack',
    nameNl: 'Lokale SEO-pakket',
    description: 'Prompts focused on geographic and neighbourhood discovery — critical for restaurants that draw from a specific area.',
    descriptionNl: 'Prompts gericht op geografische en buurtontdekking — cruciaal voor restaurants met een lokaal verzorgingsgebied.',
    category: 'Local SEO',
    tags: ['local', 'geo', 'neighbourhood', 'seo'],
    author: 'Finded',
    version: '1.0',
    prompts: [
      {
        id: 'lseo-001',
        title: 'Near me dining',
        description: '"Near me" is one of the highest-frequency restaurant search patterns.',
        template: 'What are the best {businessType}s near {location}?',
        category: 'geographic',
        language: 'en',
        tags: ['near-me', 'local', 'geographic'],
        estimatedTokens: 13,
        difficulty: 'beginner',
        useCases: ['Local intent', 'Near-me visibility'],
      },
      {
        id: 'lseo-002',
        title: 'District-level discovery',
        description: 'Tests visibility within a specific city district rather than the whole city.',
        template: 'Recommend a good {businessType} in the {location} area.',
        category: 'geographic',
        language: 'en',
        tags: ['district', 'neighbourhood', 'geographic'],
        estimatedTokens: 15,
        difficulty: 'beginner',
        useCases: ['District visibility', 'Hyper-local SEO'],
      },
      {
        id: 'lseo-003',
        title: 'Walking distance dining',
        description: 'Captures proximity-based searches where convenience is the primary driver.',
        template: 'I am staying in {location}. Where can I walk to eat?',
        category: 'geographic',
        language: 'en',
        tags: ['proximity', 'tourist', 'walking'],
        estimatedTokens: 17,
        difficulty: 'beginner',
        useCases: ['Tourist visibility', 'Proximity search'],
      },
      {
        id: 'lseo-nl-001',
        title: 'In de buurt eten',
        description: '"In de buurt" is een van de meest voorkomende zoekpatronen voor restaurants.',
        template: 'Wat zijn de beste {businessType}s in de buurt van {location}?',
        category: 'geographic',
        language: 'nl',
        tags: ['buurt', 'lokaal', 'geografisch'],
        estimatedTokens: 15,
        difficulty: 'beginner',
        useCases: ['Lokale intentie', 'Nabijheidszichtbaarheid'],
      },
    ],
  },

  // ── Occasions Pack ──────────────────────────────────────────────────────────
  {
    id: 'occasions',
    name: 'Occasions Pack',
    nameNl: 'Gelegenheidspakket',
    description: 'Occasion-driven prompts covering celebrations, business meals, family outings and seasonal events. These prompts capture the highest-value reservation intent.',
    descriptionNl: 'Gelegenheidsgestuurde prompts voor feesten, zakelijke maaltijden, familie-uitjes en seizoensgebeurtenissen.',
    category: 'Occasions',
    tags: ['occasions', 'events', 'celebrations', 'high-value'],
    author: 'Finded',
    version: '1.0',
    prompts: [
      {
        id: 'occ-001',
        title: 'Birthday dinner',
        description: 'Birthday celebrations are one of the top use cases for AI restaurant recommendations.',
        template: 'Where is a great place for a birthday dinner in {location}?',
        category: 'occasions',
        language: 'en',
        tags: ['birthday', 'celebration', 'occasion'],
        estimatedTokens: 16,
        difficulty: 'beginner',
        useCases: ['Celebration visibility', 'Special occasion'],
      },
      {
        id: 'occ-002',
        title: 'Business lunch',
        description: 'Tests visibility for professional dining — important for city-centre restaurants.',
        template: 'Where can I take a client for a business lunch in {location}?',
        category: 'occasions',
        language: 'en',
        tags: ['business', 'lunch', 'professional'],
        estimatedTokens: 17,
        difficulty: 'beginner',
        useCases: ['Business dining visibility', 'Lunch trade'],
      },
      {
        id: 'occ-003',
        title: 'Family outing with children',
        description: 'Families with children use AI recommendations frequently for dining.',
        template: 'What is a good {businessType} for families with kids in {location}?',
        category: 'occasions',
        language: 'en',
        tags: ['family', 'children', 'kid-friendly'],
        estimatedTokens: 18,
        difficulty: 'beginner',
        useCases: ['Family dining', 'Kid-friendly visibility'],
      },
      {
        id: 'occ-004',
        title: 'Anniversary dinner',
        description: 'High-value occasion with strong intent to spend — premium visibility opportunity.',
        template: 'Suggest a special restaurant in {location} for a wedding anniversary.',
        category: 'occasions',
        language: 'en',
        tags: ['anniversary', 'romantic', 'premium'],
        estimatedTokens: 16,
        difficulty: 'beginner',
        useCases: ['Anniversary dining', 'Premium occasions'],
      },
      {
        id: 'occ-nl-001',
        title: 'Verjaardagsdiner',
        description: 'Verjaardagen zijn een van de topgebruiksgevallen voor AI-restaurantaanbevelingen.',
        template: 'Waar is een geweldige plek voor een verjaardagsdiner in {location}?',
        category: 'occasions',
        language: 'nl',
        tags: ['verjaardag', 'feest', 'gelegenheid'],
        estimatedTokens: 18,
        difficulty: 'beginner',
        useCases: ['Feestzichtbaarheid', 'Speciale gelegenheid'],
      },
      {
        id: 'occ-nl-002',
        title: 'Zakelijke lunch',
        description: 'Test zichtbaarheid voor professioneel dineren — belangrijk voor restaurants in het centrum.',
        template: 'Waar kan ik een klant mee naartoe nemen voor een zakelijke lunch in {location}?',
        category: 'occasions',
        language: 'nl',
        tags: ['zakelijk', 'lunch', 'professioneel'],
        estimatedTokens: 19,
        difficulty: 'beginner',
        useCases: ['Zakelijk dinerverkeer', 'Lunchomzet'],
      },
    ],
  },

  // ── Competitor Benchmarking Pack ────────────────────────────────────────────
  {
    id: 'competitor-benchmarking',
    name: 'Competitor Benchmarking Pack',
    nameNl: 'Concurrentievergelijkingspakket',
    description: 'Prompts designed to surface which restaurants AI names as the best in a category — directly revealing your competitive landscape in AI recommendations.',
    descriptionNl: 'Prompts die laten zien welke restaurants AI als beste benoemt in een categorie — toont direct je concurrentielandschap in AI-aanbevelingen.',
    category: 'Competitor Analysis',
    tags: ['competitor', 'benchmarking', 'analysis', 'comparison'],
    author: 'Finded',
    version: '1.0',
    prompts: [
      {
        id: 'comp-001',
        title: 'Top-rated in category',
        description: 'Surfaces the top competitors in a cuisine category directly.',
        template: 'What are the top 5 {subtype} restaurants in {location} right now?',
        category: 'category',
        language: 'en',
        tags: ['top-5', 'category', 'competitor'],
        estimatedTokens: 17,
        difficulty: 'beginner',
        useCases: ['Competitor discovery', 'Category ranking'],
      },
      {
        id: 'comp-002',
        title: 'Award-winning and acclaimed',
        description: 'Tests whether AI associates your restaurant with quality accolades.',
        template: 'Which {businessType}s in {location} have won awards or are critically acclaimed?',
        category: 'trust',
        language: 'en',
        tags: ['awards', 'quality', 'reputation'],
        estimatedTokens: 18,
        difficulty: 'intermediate',
        useCases: ['Reputation benchmarking', 'Quality signals'],
      },
      {
        id: 'comp-003',
        title: 'Hidden gems comparison',
        description: 'Tests whether AI knows your restaurant as an underrated option vs popular competitors.',
        template: 'Are there any hidden gem {subtype} restaurants in {location} that locals love?',
        category: 'trust',
        language: 'en',
        tags: ['hidden-gem', 'local-favourite', 'trust'],
        estimatedTokens: 19,
        difficulty: 'intermediate',
        useCases: ['Authenticity signal', 'Local reputation'],
      },
      {
        id: 'comp-nl-001',
        title: 'Beste in categorie',
        description: 'Brengt de topconcurrenten in een keukencat direct in beeld.',
        template: 'Wat zijn de top 5 {subtype} restaurants in {location} op dit moment?',
        category: 'category',
        language: 'nl',
        tags: ['top-5', 'categorie', 'concurrent'],
        estimatedTokens: 18,
        difficulty: 'beginner',
        useCases: ['Concurrentieontdekking', 'Categorieranking'],
      },
    ],
  },

  // ── Problem-Solution Pack ───────────────────────────────────────────────────
  {
    id: 'problem-solution',
    name: 'Problem-Solution Pack',
    nameNl: 'Probleem-oplossingspakket',
    description: 'Constraint-based prompts where diners describe a specific need. These prompts reveal which restaurants AI considers versatile and capable of handling edge cases.',
    descriptionNl: 'Op beperkingen gebaseerde prompts waarbij gasten een specifieke behoefte beschrijven.',
    category: 'Problem-Solution',
    tags: ['problem-solution', 'constraints', 'dietary', 'accessibility'],
    author: 'Finded',
    version: '1.0',
    prompts: [
      {
        id: 'ps-001',
        title: 'Vegetarian / vegan options',
        description: 'Tests whether AI surfaces the restaurant for dietary-restriction queries.',
        template: 'What are the best vegetarian or vegan-friendly {businessType}s in {location}?',
        category: 'problemSolution',
        language: 'en',
        tags: ['vegetarian', 'vegan', 'dietary'],
        estimatedTokens: 17,
        difficulty: 'beginner',
        useCases: ['Dietary visibility', 'Vegan market'],
      },
      {
        id: 'ps-002',
        title: 'Outdoor seating',
        description: 'Seasonal but high-frequency query for restaurant terraces.',
        template: 'Which {businessType}s in {location} have a nice outdoor terrace?',
        category: 'problemSolution',
        language: 'en',
        tags: ['terrace', 'outdoor', 'seasonal'],
        estimatedTokens: 16,
        difficulty: 'beginner',
        useCases: ['Terrace visibility', 'Summer trade'],
      },
      {
        id: 'ps-003',
        title: 'Late-night dining',
        description: 'Tests visibility for late-night or extended-hours searches.',
        template: 'Where can I eat late at night in {location}?',
        category: 'problemSolution',
        language: 'en',
        tags: ['late-night', 'hours', 'opening-times'],
        estimatedTokens: 14,
        difficulty: 'beginner',
        useCases: ['Late-night visibility', 'Extended hours'],
      },
      {
        id: 'ps-004',
        title: 'Large group booking',
        description: 'Group dining is a high-value intent — tests whether AI knows your capacity.',
        template: 'I need to book a {businessType} for a group of 15 people in {location}. Any recommendations?',
        category: 'problemSolution',
        language: 'en',
        tags: ['group', 'booking', 'capacity'],
        estimatedTokens: 22,
        difficulty: 'intermediate',
        useCases: ['Group dining', 'Event bookings'],
      },
      {
        id: 'ps-nl-001',
        title: 'Vegetarische / veganistische opties',
        description: 'Test of AI het restaurant benoemt bij dieetvragen.',
        template: 'Wat zijn de beste vegetarische of veganistenvriendelijke {businessType}s in {location}?',
        category: 'problemSolution',
        language: 'nl',
        tags: ['vegetarisch', 'veganistisch', 'dieet'],
        estimatedTokens: 19,
        difficulty: 'beginner',
        useCases: ['Dieetvraagzichtbaarheid', 'Veganistische markt'],
      },
      {
        id: 'ps-nl-002',
        title: 'Terras met buitenzitplaatsen',
        description: 'Seizoensgevoelig maar hoge frequentievraag voor restaurantterrassen.',
        template: 'Welke {businessType}s in {location} hebben een mooi buitenterras?',
        category: 'problemSolution',
        language: 'nl',
        tags: ['terras', 'buiten', 'seizoensgebonden'],
        estimatedTokens: 17,
        difficulty: 'beginner',
        useCases: ['Terraszichtbaarheid', 'Zomerhandel'],
      },
    ],
  },

  // ── Review & Trust Pack ─────────────────────────────────────────────────────
  {
    id: 'review-trust',
    name: 'Review & Trust Pack',
    nameNl: 'Reviews & Vertrouwenspakket',
    description: 'Prompts that test how AI evaluates trust signals — reviews, ratings, reputation and social proof. Reveals whether your online presence supports AI recommendations.',
    descriptionNl: 'Prompts die testen hoe AI vertrouwenssignalen beoordeelt — reviews, beoordelingen, reputatie en sociaal bewijs.',
    category: 'Trust & Reviews',
    tags: ['trust', 'reviews', 'ratings', 'reputation', 'social-proof'],
    author: 'Finded',
    version: '1.0',
    prompts: [
      {
        id: 'rt-001',
        title: 'Highly reviewed restaurants',
        description: 'Tests whether AI associates high review count with your restaurant.',
        template: 'Which {businessType}s in {location} have the most positive reviews?',
        category: 'trust',
        language: 'en',
        tags: ['reviews', 'ratings', 'trust'],
        estimatedTokens: 15,
        difficulty: 'beginner',
        useCases: ['Review visibility', 'Reputation audit'],
      },
      {
        id: 'rt-002',
        title: 'Consistently excellent service',
        description: 'Tests whether AI mentions your restaurant in the context of service quality.',
        template: 'Which {businessType}s in {location} are known for excellent service?',
        category: 'trust',
        language: 'en',
        tags: ['service', 'quality', 'consistency'],
        estimatedTokens: 15,
        difficulty: 'intermediate',
        useCases: ['Service visibility', 'Quality signals'],
      },
      {
        id: 'rt-nl-001',
        title: 'Best beoordeelde restaurants',
        description: 'Test of AI het restaurant koppelt aan een hoog aantal positieve beoordelingen.',
        template: 'Welke {businessType}s in {location} hebben de meest positieve reviews?',
        category: 'trust',
        language: 'nl',
        tags: ['reviews', 'beoordelingen', 'vertrouwen'],
        estimatedTokens: 17,
        difficulty: 'beginner',
        useCases: ['Reviewzichtbaarheid', 'Reputatieaudit'],
      },
    ],
  },
]

// Flat list of all prompts with pack metadata for search/filter
export const ALL_PROMPTS: (MarketplacePrompt & { packId: string; packName: string; packNameNl: string })[] =
  MARKETPLACE_PACKS.flatMap(pack =>
    pack.prompts.map(p => ({ ...p, packId: pack.id, packName: pack.name, packNameNl: pack.nameNl }))
  )

export const PACK_CATEGORIES = [...new Set(MARKETPLACE_PACKS.map(p => p.category))]
