const en = {
  // Sidebar
  nav: {
    dashboard: 'Dashboard',
    restaurants: 'Restaurants',
    audits: 'Audits',
    leads: 'Leads',
    requests: 'Requests',
    prompts: 'Prompts',
    analytics: 'Analytics',
    insights: 'Insights',
    clients: 'Clients',
    users: 'Users',
    settings: 'Settings',
    upload: 'Bulk import',
    newAudit: 'New audit',
    logout: 'Log out',
  },

  // Dashboard
  dashboard: {
    title: 'Command center',
    subtitle: 'What needs action today — audit health, outreach queue, and data quality.',
    stats: {
      restaurants: 'Restaurants',
      audited: 'audited',
      readyToSend: 'Ready to send',
      readyToSendSub: 'report done, not contacted',
      followUpsDue: 'Follow-ups due',
      followUpsDueSub: 'overdue or due today',
      failedAudits: 'Failed audits',
      failedAuditsSub: 'need retry',
      inProgress: 'In progress',
      running: 'running',
      queued: 'queued',
    },
    dataQuality: 'Data quality',
    nonRestaurants: 'non-restaurant entities',
    duplicateGroups: 'duplicate groups',
    missingCity: 'missing city',
    missingCuisine: 'missing cuisine',
    possibleDuplicates: 'Possible duplicates',
    reviewEntities: 'Review entities →',
    readyForOutreach: 'Ready for outreach',
    nothingWaiting: 'Nothing waiting — every completed audit has been contacted.',
    failedAuditsRetry: 'Failed audits — retry',
    noFailedAudits: 'No failed audits.',
    followUpsDueCard: 'Follow-ups due',
    noFollowUps: 'No follow-ups due.',
    lowConfidence: 'Low-confidence audits',
    noLowConfidence: 'No low-confidence audits — evidence is solid.',
    confidence: '% confidence',
    interestedNoStep: 'Interested — no next step',
    everyInterested: 'Every interested lead has a next step scheduled.',
    topOpportunities: 'Top opportunities',
    noCompletedAudits: 'No completed audits yet.',
    allLeads: 'All leads →',
    sendReport: 'send report',
  },

  // Restaurants
  restaurants: {
    title: 'Restaurant Database',
    subtitle: 'restaurants · prospecting queue',
    bulkImport: 'Bulk import',
    newRestaurant: 'New restaurant',
    searchPlaceholder: 'Search name, website, email…',
    allStatuses: 'All statuses',
    filters: 'Filters',
    city: 'City',
    cuisine: 'Cuisine',
    plan: 'Plan',
    scoreMin: 'Score min',
    scoreMax: 'Score max',
    clear: 'Clear',
    anyPlan: 'Any',
    noRestaurantsFound: 'No restaurants found',
    adjustFilters: 'Try adjusting your filters',
    importToStart: 'Import restaurants or add one to get started',
    colRestaurant: 'Restaurant',
    colStatus: 'Status',
    colCity: 'City',
    colCuisine: 'Cuisine',
    colScore: 'Score',
    colAudits: 'Audits',
    colLastAudit: 'Last audit',
    colActions: 'Actions',
    clientView: 'Client view',
    audit: 'Audit',
    runAudit: 'Run audit',
    setStatus: 'Set status',
    exportCsv: 'Export CSV',
    selected: 'selected',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    total: 'total',
    statusLabels: {
      not_audited: 'Not audited',
      audit_queued: 'Audit queued',
      audit_complete: 'Audit complete',
      outreach_ready: 'Outreach ready',
      contacted: 'Contacted',
      customer: 'Customer',
      monitoring: 'Monitoring',
    },
  },

  // Audits
  audits: {
    title: 'Audits',
    noAuditsFound: 'No audits found',
    restaurant: 'Restaurant',
    status: 'Status',
    started: 'Started',
    completed: 'Completed',
    error: 'Error',
    actions: 'Actions',
    retryFailed: 'Retry failed',
    allStatuses: 'All',
    statusLabels: {
      all: 'All',
      queued: 'Queued',
      running: 'Running',
      completed: 'Completed',
      incomplete: 'Incomplete',
      failed: 'Failed',
    },
  },

  // Leads
  leads: {
    title: 'Leads',
    subtitle: 'restaurants',
    customers: 'customers',
    interested: 'interested',
    statusLabels: {
      not_contacted: 'Not contacted',
      email_sent: 'Email sent',
      opened: 'Opened',
      replied: 'Replied',
      interested: 'Interested',
      demo_scheduled: 'Demo scheduled',
      customer: 'Customer',
      lost: 'Lost',
    },
  },

  // Requests
  requests: {
    title: 'Audit requests',
    subtitle: 'Submitted from the public funnel at',
    noRequests: 'No requests yet.',
    colName: 'Name',
    colWebsite: 'Website',
    colCity: 'City',
    colContact: 'Contact',
    colStatus: 'Status',
    colDate: 'Date',
    colActions: 'Actions',
  },

  // Prompts
  prompts: {
    title: 'Prompts',
  },

  // Analytics
  analytics: {
    title: 'Analytics',
    restaurants: 'Restaurants',
    auditsRun: 'Audits run',
    completed: 'completed',
    avgVisibility: 'Avg visibility',
    avgOpportunity: 'Avg opportunity',
    avgMentionRate: 'Avg mention rate',
    scoredAudits: 'Scored audits',
    missingScores: 'Missing scores',
    completedNoScore: 'completed but no score',
    failedAudits: 'Failed audits',
    signals: {
      schemaMarkup: 'Schema markup',
      menuPresent: 'Menu present',
      openingHours: 'Opening hours',
      reservationLinks: 'Reservation links',
      socialLinks: 'Social links',
    },
  },

  // Insights
  insights: {
    title: 'Industry insights',
    subtitle: 'Aggregate, anonymized intelligence from every audit — the data ChatGPT doesn\'t have.',
    filterCuisine: 'Cuisine',
    filterCity: 'City',
    filterPeriod: 'Period',
    filterRecommended: 'Recommended',
    avgVisibility: 'Avg visibility',
    avgMentionFreq: 'Avg mention freq.',
    audits: 'Audits',
    byCuisine: 'By cuisine',
    byCity: 'By city',
  },

  // Clients
  clients: {
    title: 'Clients',
    subtitle: 'paying · at risk · avg health',
    addClient: 'Add client',
    colName: 'Name',
    colPlan: 'Plan',
    colHealth: 'Health',
    colRevenue: 'Revenue',
    colAudits: 'Audits',
    colLastActive: 'Last active',
    colActions: 'Actions',
    noClients: 'No clients yet',
    addFirstClient: 'Click "Add client" to get started',
    plans: {
      free: 'Free',
      beta: 'Beta Tester',
      audit: 'Audit',
      implementation: 'Implementation',
    },
    modal: {
      title: 'Add client',
      name: 'Restaurant name',
      email: 'Email',
      city: 'City',
      cuisine: 'Cuisine',
      plan: 'Plan',
      cancel: 'Cancel',
      create: 'Create client',
    },
    healthBands: {
      healthy: 'Healthy',
      at_risk: 'At risk',
      churned: 'Churned',
    },
  },

  // Users
  users: {
    title: 'Users & access',
    subtitle: 'Per-user accounts and roles. The shared password still works as a bootstrap admin until you add accounts.',
    addUser: 'Add a user',
    email: 'Email',
    password: 'Password',
    role: 'Role',
    roleHelp: 'Admin = full access incl. user management · Operator = normal backoffice · Viewer = read-only.',
    addUserBtn: 'Add user',
    adminsOnly: 'Admins only',
    adminsOnlyDesc: 'User management requires the admin role. Ask an admin to grant access.',
    colEmail: 'Email',
    colRole: 'Role',
    colCreated: 'Created',
    colLastLogin: 'Last login',
    colActions: 'Actions',
    never: 'Never',
    deleteConfirm: 'Delete this user?',
  },

  // Settings
  settings: {
    title: 'Settings',
    subtitle: 'Defaults applied across reports, audits and the public site.',
    language: 'Language',
    defaultLanguageLabel: 'Default language for reports & audits',
    forceLanguage: 'Force language',
    forceLanguageDesc: 'When on, every report and audit uses the default language above, ignoring the restaurant\'s country. Turn off to pick the language per restaurant by country (NL/BE → Dutch, else English).',
    contact: 'Contact',
    branding: 'Branding',
    save: 'Save',
    saved: 'Saved',
    loading: 'Loading…',
  },

  // Upload
  upload: {
    title: 'Bulk import',
    steps: ['Upload', 'Preview & dedupe', 'Import'],
    dropzone: 'Drop a CSV or Excel file here, or click to browse',
    preview: 'Preview',
    import: 'Import',
    back: 'Back',
    importing: 'Importing…',
    noPreview: 'No preview yet',
  },

  // New restaurant
  newRestaurant: {
    title: 'Add restaurant',
    name: 'Restaurant name',
    website: 'Website',
    email: 'Email',
    phone: 'Phone',
    city: 'City',
    cuisine: 'Cuisine',
    cancel: 'Cancel',
    create: 'Create & run audit',
  },

  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    loading: 'Loading…',
    error: 'Something went wrong',
    success: 'Done',
    never: 'Never',
    unknown: 'Unknown',
  },
}

const nl: typeof en = {
  nav: {
    dashboard: 'Dashboard',
    restaurants: 'Restaurants',
    audits: 'Audits',
    leads: 'Leads',
    requests: 'Aanvragen',
    prompts: 'Prompts',
    analytics: 'Analytics',
    insights: 'Inzichten',
    clients: 'Klanten',
    users: 'Gebruikers',
    settings: 'Instellingen',
    upload: 'Bulk import',
    newAudit: 'Nieuwe audit',
    logout: 'Uitloggen',
  },

  dashboard: {
    title: 'Commandocentrum',
    subtitle: 'Wat heeft vandaag aandacht nodig — auditstatus, outreachqueue en datakwaliteit.',
    stats: {
      restaurants: 'Restaurants',
      audited: 'geauditeerd',
      readyToSend: 'Klaar om te sturen',
      readyToSendSub: 'rapport klaar, nog niet gecontacteerd',
      followUpsDue: 'Opvolgingen gepland',
      followUpsDueSub: 'verlopen of vandaag gepland',
      failedAudits: 'Mislukte audits',
      failedAuditsSub: 'opnieuw proberen',
      inProgress: 'In uitvoering',
      running: 'actief',
      queued: 'in wachtrij',
    },
    dataQuality: 'Datakwaliteit',
    nonRestaurants: 'niet-restaurant entiteiten',
    duplicateGroups: 'duplicaatgroepen',
    missingCity: 'stad ontbreekt',
    missingCuisine: 'keuken ontbreekt',
    possibleDuplicates: 'Mogelijke duplicaten',
    reviewEntities: 'Entiteiten bekijken →',
    readyForOutreach: 'Klaar voor outreach',
    nothingWaiting: 'Niets wacht — elke voltooide audit is al gecontacteerd.',
    failedAuditsRetry: 'Mislukte audits — opnieuw proberen',
    noFailedAudits: 'Geen mislukte audits.',
    followUpsDueCard: 'Opvolgingen gepland',
    noFollowUps: 'Geen opvolgingen gepland.',
    lowConfidence: 'Lage-betrouwbaarheidsaudits',
    noLowConfidence: 'Geen lage-betrouwbaarheidsaudits — bewijs is solide.',
    confidence: '% betrouwbaarheid',
    interestedNoStep: 'Geïnteresseerd — geen volgende stap',
    everyInterested: 'Elke geïnteresseerde lead heeft een volgende stap gepland.',
    topOpportunities: 'Topkansen',
    noCompletedAudits: 'Nog geen voltooide audits.',
    allLeads: 'Alle leads →',
    sendReport: 'rapport sturen',
  },

  restaurants: {
    title: 'Restaurantdatabase',
    subtitle: 'restaurants · prospecting-wachtrij',
    bulkImport: 'Bulk import',
    newRestaurant: 'Nieuw restaurant',
    searchPlaceholder: 'Zoek naam, website, e-mail…',
    allStatuses: 'Alle statussen',
    filters: 'Filters',
    city: 'Stad',
    cuisine: 'Keuken',
    plan: 'Plan',
    scoreMin: 'Score min',
    scoreMax: 'Score max',
    clear: 'Wissen',
    anyPlan: 'Alle',
    noRestaurantsFound: 'Geen restaurants gevonden',
    adjustFilters: 'Pas je filters aan',
    importToStart: 'Importeer restaurants of voeg er een toe om te beginnen',
    colRestaurant: 'Restaurant',
    colStatus: 'Status',
    colCity: 'Stad',
    colCuisine: 'Keuken',
    colScore: 'Score',
    colAudits: 'Audits',
    colLastAudit: 'Laatste audit',
    colActions: 'Acties',
    clientView: 'Klantweergave',
    audit: 'Audit',
    runAudit: 'Audit starten',
    setStatus: 'Status instellen',
    exportCsv: 'CSV exporteren',
    selected: 'geselecteerd',
    previous: 'Vorige',
    next: 'Volgende',
    page: 'Pagina',
    of: 'van',
    total: 'totaal',
    statusLabels: {
      not_audited: 'Niet geauditeerd',
      audit_queued: 'Audit in wachtrij',
      audit_complete: 'Audit voltooid',
      outreach_ready: 'Klaar voor outreach',
      contacted: 'Gecontacteerd',
      customer: 'Klant',
      monitoring: 'Monitoring',
    },
  },

  audits: {
    title: 'Audits',
    noAuditsFound: 'Geen audits gevonden',
    restaurant: 'Restaurant',
    status: 'Status',
    started: 'Gestart',
    completed: 'Voltooid',
    error: 'Fout',
    actions: 'Acties',
    retryFailed: 'Mislukte herstarten',
    allStatuses: 'Alle',
    statusLabels: {
      all: 'Alle',
      queued: 'In wachtrij',
      running: 'Actief',
      completed: 'Voltooid',
      incomplete: 'Onvolledig',
      failed: 'Mislukt',
    },
  },

  leads: {
    title: 'Leads',
    subtitle: 'restaurants',
    customers: 'klanten',
    interested: 'geïnteresseerd',
    statusLabels: {
      not_contacted: 'Niet gecontacteerd',
      email_sent: 'E-mail verstuurd',
      opened: 'Geopend',
      replied: 'Gereageerd',
      interested: 'Geïnteresseerd',
      demo_scheduled: 'Demo gepland',
      customer: 'Klant',
      lost: 'Verloren',
    },
  },

  requests: {
    title: 'Auditaanvragen',
    subtitle: 'Ingediend via de publieke funnel op',
    noRequests: 'Nog geen aanvragen.',
    colName: 'Naam',
    colWebsite: 'Website',
    colCity: 'Stad',
    colContact: 'Contact',
    colStatus: 'Status',
    colDate: 'Datum',
    colActions: 'Acties',
  },

  prompts: {
    title: 'Prompts',
  },

  analytics: {
    title: 'Analytics',
    restaurants: 'Restaurants',
    auditsRun: 'Audits uitgevoerd',
    completed: 'voltooid',
    avgVisibility: 'Gem. zichtbaarheid',
    avgOpportunity: 'Gem. kans',
    avgMentionRate: 'Gem. vermeldingsrate',
    scoredAudits: 'Gescoorde audits',
    missingScores: 'Ontbrekende scores',
    completedNoScore: 'voltooid maar geen score',
    failedAudits: 'Mislukte audits',
    signals: {
      schemaMarkup: 'Schema-opmaak',
      menuPresent: 'Menu aanwezig',
      openingHours: 'Openingstijden',
      reservationLinks: 'Reserveringslinks',
      socialLinks: 'Sociale links',
    },
  },

  insights: {
    title: 'Branche-inzichten',
    subtitle: 'Geaggregeerde, geanonimiseerde inzichten uit elke audit — data die ChatGPT niet heeft.',
    filterCuisine: 'Keuken',
    filterCity: 'Stad',
    filterPeriod: 'Periode',
    filterRecommended: 'Aanbevolen',
    avgVisibility: 'Gem. zichtbaarheid',
    avgMentionFreq: 'Gem. vermeldingsfrequentie',
    audits: 'Audits',
    byCuisine: 'Per keuken',
    byCity: 'Per stad',
  },

  clients: {
    title: 'Klanten',
    subtitle: 'betalend · risico · gem. gezondheid',
    addClient: 'Klant toevoegen',
    colName: 'Naam',
    colPlan: 'Plan',
    colHealth: 'Gezondheid',
    colRevenue: 'Omzet',
    colAudits: 'Audits',
    colLastActive: 'Laatste activiteit',
    colActions: 'Acties',
    noClients: 'Nog geen klanten',
    addFirstClient: 'Klik op "Klant toevoegen" om te beginnen',
    plans: {
      free: 'Gratis',
      beta: 'Beta Tester',
      audit: 'Audit',
      implementation: 'Implementatie',
    },
    modal: {
      title: 'Klant toevoegen',
      name: 'Restaurantnaam',
      email: 'E-mail',
      city: 'Stad',
      cuisine: 'Keuken',
      plan: 'Plan',
      cancel: 'Annuleren',
      create: 'Klant aanmaken',
    },
    healthBands: {
      healthy: 'Gezond',
      at_risk: 'Risico',
      churned: 'Verloren',
    },
  },

  users: {
    title: 'Gebruikers & toegang',
    subtitle: 'Per-gebruikersaccounts en rollen. Het gedeelde wachtwoord werkt nog als bootstrap-admin totdat je accounts toevoegt.',
    addUser: 'Gebruiker toevoegen',
    email: 'E-mail',
    password: 'Wachtwoord',
    role: 'Rol',
    roleHelp: 'Admin = volledige toegang incl. gebruikersbeheer · Operator = normaal backoffice · Viewer = alleen lezen.',
    addUserBtn: 'Gebruiker toevoegen',
    adminsOnly: 'Alleen admins',
    adminsOnlyDesc: 'Gebruikersbeheer vereist de adminrol. Vraag een admin om toegang.',
    colEmail: 'E-mail',
    colRole: 'Rol',
    colCreated: 'Aangemaakt',
    colLastLogin: 'Laatste login',
    colActions: 'Acties',
    never: 'Nooit',
    deleteConfirm: 'Gebruiker verwijderen?',
  },

  settings: {
    title: 'Instellingen',
    subtitle: 'Standaardwaarden voor rapporten, audits en de publieke site.',
    language: 'Taal',
    defaultLanguageLabel: 'Standaardtaal voor rapporten & audits',
    forceLanguage: 'Taal forceren',
    forceLanguageDesc: 'Wanneer aan, gebruikt elk rapport en elke audit de bovenstaande standaardtaal, ongeacht het land van het restaurant. Zet uit om de taal per restaurant op te kiezen op land (NL/BE → Nederlands, anders Engels).',
    contact: 'Contact',
    branding: 'Huisstijl',
    save: 'Opslaan',
    saved: 'Opgeslagen',
    loading: 'Laden…',
  },

  upload: {
    title: 'Bulk import',
    steps: ['Uploaden', 'Voorbeeld & deduplicatie', 'Importeren'],
    dropzone: 'Sleep een CSV- of Excel-bestand hierheen of klik om te bladeren',
    preview: 'Voorbeeld',
    import: 'Importeren',
    back: 'Terug',
    importing: 'Importeren…',
    noPreview: 'Nog geen voorbeeld',
  },

  newRestaurant: {
    title: 'Restaurant toevoegen',
    name: 'Restaurantnaam',
    website: 'Website',
    email: 'E-mail',
    phone: 'Telefoon',
    city: 'Stad',
    cuisine: 'Keuken',
    cancel: 'Annuleren',
    create: 'Aanmaken & audit starten',
  },

  common: {
    save: 'Opslaan',
    cancel: 'Annuleren',
    delete: 'Verwijderen',
    edit: 'Bewerken',
    view: 'Bekijken',
    loading: 'Laden…',
    error: 'Er ging iets mis',
    success: 'Klaar',
    never: 'Nooit',
    unknown: 'Onbekend',
  },
}

export const ADMIN_COPY = { en, nl } as const
export type AdminLang = keyof typeof ADMIN_COPY
export type AdminCopy = typeof en
