import type { Language } from './i18n'

/**
 * Portal/client-dashboard copy (NL/EN). Plain data, no server imports — safe in
 * both server pages and client components. Keyed by language.
 */
export const PORTAL = {
  en: {
    login: {
      title: 'Sign in to your dashboard',
      sub: "Enter your email and we'll send you a secure sign-in link — no password needed.",
      email: 'Email', placeholder: 'you@restaurant.com', send: 'Send me a sign-in link',
      sentTitle: 'Check your email',
      sentBody: (e: string) => `We sent a sign-in link to ${e}. It works once and expires in 30 minutes.`,
      errExpired: 'That link has expired or was already used. Enter your email for a fresh one.',
      errConfig: 'Login is temporarily unavailable. Please try again later.',
      errGeneric: 'Something went wrong', errSend: 'Could not send the link',
    },
    list: {
      title: 'Your restaurants', sub: 'Open a restaurant to see its AI Visibility dashboard.',
      emptyTitle: 'No restaurants linked yet',
      emptyBody: "We link dashboards to the email your audit was requested with. If your audit is still running, or you used a different email, it may not appear yet. Start a free check from the homepage, or reply to your audit email and we'll connect it.",
      startCheck: 'Start a free check', logout: 'Log out',
      auditedOn: (d: string) => `audited ${d}`, notAudited: 'not audited yet',
      plan: { free: 'Free', audit: 'Audit', implementation: 'Implementation' } as Record<string, string>,
    },
    detail: {
      allRestaurants: 'All restaurants', backOffice: 'Back to backoffice',
      adminPreview: 'Admin preview — this is exactly what the client sees.', adminPreviewShort: 'Admin preview',
    },
    dash: {
      nav: ['Overview', 'AI Visibility Score', 'AI Mentions', 'Competitors', 'Recommendations', 'Website Audit', 'Trends (Beta)'],
      fullReport: 'Full report & PDF',
      preparingTitle: 'Your audit is being prepared',
      preparingBody: 'As soon as your AI Visibility audit completes, your score, competitors and recommendations appear here.',
      bandGood: 'Good', bandFair: 'Fair', bandWork: 'Needs work',
      scoreOverviewBody: 'How visible you are in AI recommendations today.',
      mentioned: 'Mentioned by AI',
      mentionedBody: (p: number, c: number) => `You appear in ${p}% of the AI answers we tested. ${c} of 4 models name you.`,
      topCompetitors: 'Top Competitors', noneExtracted: 'None extracted.',
      overTime: 'Visibility over time',
      overTimeEmpty: 'Your visibility over time will appear here as more audits run. Monthly monitoring is coming soon.',
      keyInsight: 'Key insight', reliability: 'Reliability', relHigh: 'High', relMed: 'Medium', relLow: 'Low',
      relCaption: 'How many AI calls completed',
      scoreTitle: 'AI Visibility Score',
      scoreLong: (c: number | string) => `A weighted measure of how visible you are in AI recommendations. Confidence ${c}% — based on how much data backed this audit.`,
      breaksDown: 'How it breaks down', weight: 'weight', breakdownNA: 'Breakdown not available.',
      mentionsTitle: 'AI Mentions — by model',
      mentionsSub: (c: number) => `How often each assistant named you across the prompts we tested. ${c} of 4 models mention you.`,
      mentionOne: 'mention', mentionMany: 'mentions', avgPos: 'avg pos',
      competitorsTitle: 'Competitors recommended by AI',
      competitorsSub: 'Restaurants the assistants named, by how many times they appeared.',
      noCompetitors: 'No competitors were extracted from this audit.',
      recsEmpty: 'Recommendations appear here once generated for this audit.',
      doFirst: 'Do first', doNext: 'Do next', optional: 'Optional', confidence: 'confidence', impact: 'impact', effort: 'effort',
      websiteTitle: 'Website signals for AI',
      websiteSub: 'What AI crawlers can read on your site — the building blocks of being understood and recommended.',
      noWebsite: 'No website audit available.',
      sig: { schema: 'Restaurant schema (Schema.org)', menu: 'Crawlable menu', hours: 'Opening hours', reservation: 'Reservation link', faq: 'FAQ content', reviews: 'Review signals', location: 'Clear location', social: 'Social links' },
      metaTitle: 'Meta title', openFull: 'Open full report & recommendations',
    },
    mon: {
      since: (d: number) => `${d > 0 ? '+' : ''}${d} since last audit`,
      monthly: (d: number) => `${d > 0 ? '+' : ''}${d} this month`,
      lastUpdated: (d: string) => `Last updated ${d}`,
      runs: (n: number) => `${n} monitoring run${n === 1 ? '' : 's'}`,
      changedTitle: "What's changed",
      changedSince: 'Measured changes since your previous audit.',
      changedEmpty: 'No measurable changes since your last audit. We compare every new audit against the previous one — changes appear here automatically.',
      chg: {
        visUp: (v: number) => `Visibility increased by ${v} points`,
        visDown: (v: number) => `Visibility dropped by ${v} points`,
        provUp: (n: string) => `${n} now recommends your restaurant`,
        provDown: (n: string) => `${n} stopped recommending you`,
        sigUp: (l: string) => `${l} now detected on your site`,
        sigDown: (l: string) => `${l} no longer detected`,
        menUp: (v: number) => `AI mention frequency up ${v}%`,
        menDown: (v: number) => `AI mention frequency down ${v}%`,
      },
      oppTitle: 'Your biggest opportunities',
      oppSub: 'Ranked by measured impact across restaurants like yours — never generic advice.',
      oppEmpty: 'No measured opportunities right now — your site already carries the signals that matter most.',
      oppGain: 'Expected gain', oppConf: 'Confidence', oppMeasured: 'Restaurants measured',
      oppDiff: 'Difficulty', oppEst: 'Est. time', mins: (m: number) => `${m} min`,
      diff: { easy: 'Easy', medium: 'Medium', hard: 'Hard' } as Record<string, string>,
      cmpTitle: 'How you compare',
      cmpSub: 'Your AI visibility against anonymized benchmarks from the warehouse.',
      cmpAvg: 'Average', cmpYou: 'You', cmpTop10: 'Top 10%', cmpRec: 'Avg. recommendation rate', cmpYourRec: 'Your rate',
      scope: { overall: 'All restaurants', cuisine: 'Restaurants like yours', city: 'In your city' } as Record<string, string>,
      provTitle: 'Provider breakdown',
      provSub: 'How each assistant recommends you, and how that is trending.',
      provTrend: { up: 'Trending up', down: 'Trending down', flat: 'Stable' } as Record<string, string>,
      provStability: 'Stability', provAvgPos: 'Avg. position', provCites: 'Cited sources', provNoCites: 'No sources cited.',
      provResponses: (n: number) => `${n} responses`,
      indTitle: 'What Finded learned this month',
      indSub: 'Statistically significant findings across all restaurants we measure.',
      indEmpty: 'No findings clear the significance gate yet. They appear as the dataset grows.',
      find: {
        corrUp: (pct: number, l: string) => `Restaurants with ${l} are recommended ${pct}% more often`,
        corrDown: (pct: number, l: string) => `${l} now correlates with ${pct}% fewer recommendations`,
        trendUp: (pct: number) => `AI visibility is rising ${pct} points/month industry-wide`,
        trendDown: (pct: number) => `AI visibility is falling ${pct} points/month industry-wide`,
      },
      findMeta: (n: number, c: number | null) => `${n.toLocaleString()} restaurants${c != null ? ` · ${Math.round(c * 100)}% confidence` : ''}`,
      resTitle: 'Latest industry discoveries',
      histTitle: 'Visibility history',
      histEvent: { signal_added: (l: string) => `${l} added`, signal_removed: (l: string) => `${l} removed` },
      lockedBody: 'Unlock with continuous AI Visibility Monitoring.',
      upgrade: 'Upgrade to unlock',
      locked: ['Full provider analysis', 'Industry benchmarks', 'Evidence & citations', 'Opportunity scoring', 'Research insights', 'Competitor breakdown'],
      savedTitle: 'Saved questions', savedSoon: 'Coming soon — track how AI answers the questions your guests actually ask, monitored every month.',
      savedExamples: ['best Italian restaurant Amsterdam', 'romantic dinner Rotterdam', 'business lunch Utrecht'],
      cadence: 'Monthly monitoring', nextCheck: (d: string) => `Next check ~ ${d}`,
      provDriftFlag: 'Model drift', provRanking: 'Ranking position',
      compTitle: 'Competitors on the move', compGaining: 'Gaining visibility', compLosing: 'Losing visibility',
      compNew: 'new', compNamed: (n: number) => `named ${n}×`,
      compEmpty: 'Not enough history yet to show competitor movement — it appears after your next monitoring run.',
    },
  },
  nl: {
    login: {
      title: 'Log in op je dashboard',
      sub: 'Vul je e-mailadres in en we sturen je een veilige inloglink — geen wachtwoord nodig.',
      email: 'E-mail', placeholder: 'jij@restaurant.nl', send: 'Stuur me een inloglink',
      sentTitle: 'Check je e-mail',
      sentBody: (e: string) => `We hebben een inloglink naar ${e} gestuurd. Hij werkt één keer en verloopt na 30 minuten.`,
      errExpired: 'Die link is verlopen of al gebruikt. Vul je e-mailadres in voor een nieuwe.',
      errConfig: 'Inloggen is tijdelijk niet beschikbaar. Probeer het later opnieuw.',
      errGeneric: 'Er ging iets mis', errSend: 'Kon de link niet versturen',
    },
    list: {
      title: 'Jouw restaurants', sub: 'Open een restaurant om het AI-zichtbaarheidsdashboard te zien.',
      emptyTitle: 'Nog geen restaurants gekoppeld',
      emptyBody: 'We koppelen dashboards aan het e-mailadres waarmee je audit is aangevraagd. Als je audit nog loopt of je een ander adres gebruikte, verschijnt het mogelijk nog niet. Start een gratis check op de homepage, of beantwoord je auditmail dan koppelen we het.',
      startCheck: 'Start een gratis check', logout: 'Uitloggen',
      auditedOn: (d: string) => `geaudit ${d}`, notAudited: 'nog niet geaudit',
      plan: { free: 'Gratis', audit: 'Audit', implementation: 'Implementatie' } as Record<string, string>,
    },
    detail: {
      allRestaurants: 'Alle restaurants', backOffice: 'Terug naar backoffice',
      adminPreview: 'Adminvoorbeeld — dit is precies wat de klant ziet.', adminPreviewShort: 'Adminvoorbeeld',
    },
    dash: {
      nav: ['Overzicht', 'AI-zichtbaarheidsscore', 'AI-vermeldingen', 'Concurrenten', 'Aanbevelingen', 'Website-audit', 'Trends (Bèta)'],
      fullReport: 'Volledig rapport & PDF',
      preparingTitle: 'Je audit wordt voorbereid',
      preparingBody: 'Zodra je AI-zichtbaarheidsaudit klaar is, verschijnen je score, concurrenten en aanbevelingen hier.',
      bandGood: 'Goed', bandFair: 'Redelijk', bandWork: 'Aandacht nodig',
      scoreOverviewBody: 'Hoe zichtbaar je vandaag bent in AI-aanbevelingen.',
      mentioned: 'Genoemd door AI',
      mentionedBody: (p: number, c: number) => `Je verschijnt in ${p}% van de geteste AI-antwoorden. ${c} van de 4 modellen noemen je.`,
      topCompetitors: 'Top concurrenten', noneExtracted: 'Geen gevonden.',
      overTime: 'Zichtbaarheid over tijd',
      overTimeEmpty: 'Je zichtbaarheid over tijd verschijnt hier naarmate er meer audits draaien. Maandelijkse monitoring komt eraan.',
      keyInsight: 'Belangrijkste inzicht', reliability: 'Betrouwbaarheid', relHigh: 'Hoog', relMed: 'Gemiddeld', relLow: 'Laag',
      relCaption: 'Hoeveel AI-calls voltooid zijn',
      scoreTitle: 'AI-zichtbaarheidsscore',
      scoreLong: (c: number | string) => `Een gewogen maat voor hoe zichtbaar je bent in AI-aanbevelingen. Betrouwbaarheid ${c}% — op basis van hoeveel data deze audit onderbouwde.`,
      breaksDown: 'Hoe het is opgebouwd', weight: 'weging', breakdownNA: 'Opbouw niet beschikbaar.',
      mentionsTitle: 'AI-vermeldingen — per model',
      mentionsSub: (c: number) => `Hoe vaak elke assistent je noemde over de geteste prompts. ${c} van de 4 modellen noemen je.`,
      mentionOne: 'vermelding', mentionMany: 'vermeldingen', avgPos: 'gem. positie',
      competitorsTitle: 'Concurrenten die AI aanbeveelt',
      competitorsSub: 'Restaurants die de assistenten noemden, op aantal keer dat ze verschenen.',
      noCompetitors: 'Er zijn geen concurrenten uit deze audit gehaald.',
      recsEmpty: 'Aanbevelingen verschijnen hier zodra ze voor deze audit zijn gegenereerd.',
      doFirst: 'Eerst doen', doNext: 'Daarna', optional: 'Optioneel', confidence: 'betrouwbaarheid', impact: 'impact', effort: 'inspanning',
      websiteTitle: 'Websitesignalen voor AI',
      websiteSub: 'Wat AI-crawlers op je site kunnen lezen — de bouwstenen om begrepen en aanbevolen te worden.',
      noWebsite: 'Geen website-audit beschikbaar.',
      sig: { schema: 'Restaurant-schema (Schema.org)', menu: 'Crawlbaar menu', hours: 'Openingstijden', reservation: 'Reserveringslink', faq: 'FAQ-inhoud', reviews: 'Reviewsignalen', location: 'Duidelijke locatie', social: 'Social links' },
      metaTitle: 'Meta-titel', openFull: 'Open volledig rapport & aanbevelingen',
    },
    mon: {
      since: (d: number) => `${d > 0 ? '+' : ''}${d} sinds vorige audit`,
      monthly: (d: number) => `${d > 0 ? '+' : ''}${d} deze maand`,
      lastUpdated: (d: string) => `Laatst bijgewerkt ${d}`,
      runs: (n: number) => `${n} monitoringrun${n === 1 ? '' : 's'}`,
      changedTitle: 'Wat is er veranderd',
      changedSince: 'Gemeten veranderingen sinds je vorige audit.',
      changedEmpty: 'Geen meetbare veranderingen sinds je laatste audit. We vergelijken elke nieuwe audit met de vorige — veranderingen verschijnen hier automatisch.',
      chg: {
        visUp: (v: number) => `Zichtbaarheid met ${v} punten gestegen`,
        visDown: (v: number) => `Zichtbaarheid met ${v} punten gedaald`,
        provUp: (n: string) => `${n} beveelt je restaurant nu aan`,
        provDown: (n: string) => `${n} noemt je niet meer`,
        sigUp: (l: string) => `${l} nu gedetecteerd op je site`,
        sigDown: (l: string) => `${l} niet meer gedetecteerd`,
        menUp: (v: number) => `AI-vermeldingen ${v}% gestegen`,
        menDown: (v: number) => `AI-vermeldingen ${v}% gedaald`,
      },
      oppTitle: 'Je grootste kansen',
      oppSub: 'Gerangschikt op gemeten impact bij restaurants zoals dat van jou — nooit generiek advies.',
      oppEmpty: 'Op dit moment geen gemeten kansen — je site heeft de belangrijkste signalen al.',
      oppGain: 'Verwachte winst', oppConf: 'Betrouwbaarheid', oppMeasured: 'Restaurants gemeten',
      oppDiff: 'Moeilijkheid', oppEst: 'Geschatte tijd', mins: (m: number) => `${m} min`,
      diff: { easy: 'Makkelijk', medium: 'Gemiddeld', hard: 'Moeilijk' } as Record<string, string>,
      cmpTitle: 'Hoe je je verhoudt',
      cmpSub: 'Je AI-zichtbaarheid tegenover geanonimiseerde benchmarks uit het warehouse.',
      cmpAvg: 'Gemiddeld', cmpYou: 'Jij', cmpTop10: 'Top 10%', cmpRec: 'Gem. aanbevelingsratio', cmpYourRec: 'Jouw ratio',
      scope: { overall: 'Alle restaurants', cuisine: 'Restaurants zoals dat van jou', city: 'In jouw stad' } as Record<string, string>,
      provTitle: 'Per AI-assistent',
      provSub: 'Hoe elke assistent je aanbeveelt en welke kant dat op gaat.',
      provTrend: { up: 'Stijgend', down: 'Dalend', flat: 'Stabiel' } as Record<string, string>,
      provStability: 'Stabiliteit', provAvgPos: 'Gem. positie', provCites: 'Genoemde bronnen', provNoCites: 'Geen bronnen genoemd.',
      provResponses: (n: number) => `${n} antwoorden`,
      indTitle: 'Wat Finded deze maand leerde',
      indSub: 'Statistisch significante bevindingen over alle restaurants die we meten.',
      indEmpty: 'Nog geen bevindingen die de significantiedrempel halen. Ze verschijnen naarmate de dataset groeit.',
      find: {
        corrUp: (pct: number, l: string) => `Restaurants met ${l} worden ${pct}% vaker aanbevolen`,
        corrDown: (pct: number, l: string) => `${l} hangt nu samen met ${pct}% minder aanbevelingen`,
        trendUp: (pct: number) => `AI-zichtbaarheid stijgt ${pct} punten/maand in de hele sector`,
        trendDown: (pct: number) => `AI-zichtbaarheid daalt ${pct} punten/maand in de hele sector`,
      },
      findMeta: (n: number, c: number | null) => `${n.toLocaleString()} restaurants${c != null ? ` · ${Math.round(c * 100)}% betrouwbaarheid` : ''}`,
      resTitle: 'Laatste sectorinzichten',
      histTitle: 'Zichtbaarheidsgeschiedenis',
      histEvent: { signal_added: (l: string) => `${l} toegevoegd`, signal_removed: (l: string) => `${l} verwijderd` },
      lockedBody: 'Ontgrendel met continue AI-zichtbaarheidsmonitoring.',
      upgrade: 'Upgrade om te ontgrendelen',
      locked: ['Volledige AI-analyse', 'Sector-benchmarks', 'Bewijs & citaties', 'Kansenscore', 'Onderzoeksinzichten', 'Concurrentie-analyse'],
      savedTitle: 'Opgeslagen vragen', savedSoon: 'Binnenkort — volg hoe AI de vragen beantwoordt die je gasten echt stellen, elke maand gemonitord.',
      savedExamples: ['beste Italiaanse restaurant Amsterdam', 'romantisch diner Rotterdam', 'zakenlunch Utrecht'],
      cadence: 'Maandelijkse monitoring', nextCheck: (d: string) => `Volgende check ~ ${d}`,
      provDriftFlag: 'Modeldrift', provRanking: 'Rankingpositie',
      compTitle: 'Concurrenten in beweging', compGaining: 'Wint zichtbaarheid', compLosing: 'Verliest zichtbaarheid',
      compNew: 'nieuw', compNamed: (n: number) => `${n}× genoemd`,
      compEmpty: 'Nog niet genoeg historie om beweging te tonen — verschijnt na je volgende monitoringrun.',
    },
  },
} satisfies Record<Language, unknown>
