import type { Language } from './i18n'

/**
 * Portal/client-dashboard copy (NL/EN). Plain data, no server imports — safe in
 * both server pages and client components. Keyed by language.
 */
export const PORTAL = {
  en: {
    login: {
      title: 'Sign in to your dashboard',
      sub: "Enter your email and we'll send you a secure sign-in link — no password needed.",
      email: 'Email', placeholder: 'you@restaurant.com', send: 'Send me a sign-in link',
      sentTitle: 'Check your email',
      sentBody: (e: string) => `We sent a sign-in link to ${e}. It works once and expires in 30 minutes.`,
      errExpired: 'That link has expired or was already used. Enter your email for a fresh one.',
      errConfig: 'Login is temporarily unavailable. Please try again later.',
      errGeneric: 'Something went wrong', errSend: 'Could not send the link',
    },
    list: {
      title: 'Your restaurants', sub: 'Open a restaurant to see its AI Visibility dashboard.',
      emptyTitle: 'No restaurants linked yet',
      emptyBody: "We link dashboards to the email your audit was requested with. If your audit is still running, or you used a different email, it may not appear yet. Start a free check from the homepage, or reply to your audit email and we'll connect it.",
      startCheck: 'Start a free check', logout: 'Log out',
      auditedOn: (d: string) => `audited ${d}`, notAudited: 'not audited yet',
      plan: { free: 'Free', audit: 'Audit', implementation: 'Implementation' } as Record<string, string>,
    },
    detail: {
      allRestaurants: 'All restaurants', backOffice: 'Back to backoffice',
      adminPreview: 'Admin preview — this is exactly what the client sees.', adminPreviewShort: 'Admin preview',
    },
    dash: {
      nav: ['Overview', 'AI Visibility Score', 'AI Mentions', 'Competitors', 'Recommendations', 'Website Audit', 'Trends (Beta)'],
      fullReport: 'Full report & PDF',
      preparingTitle: 'Your audit is being prepared',
      preparingBody: 'As soon as your AI Visibility audit completes, your score, competitors and recommendations appear here.',
      bandGood: 'Good', bandFair: 'Fair', bandWork: 'Needs work',
      scoreOverviewBody: 'How visible you are in AI recommendations today.',
      mentioned: 'Mentioned by AI',
      mentionedBody: (p: number, c: number) => `You appear in ${p}% of the AI answers we tested. ${c} of 4 models name you.`,
      topCompetitors: 'Top Competitors', noneExtracted: 'None extracted.',
      overTime: 'Visibility over time',
      overTimeEmpty: 'Your visibility over time will appear here as more audits run. Monthly monitoring is coming soon.',
      keyInsight: 'Key insight', reliability: 'Reliability', relHigh: 'High', relMed: 'Medium', relLow: 'Low',
      relCaption: 'How many AI calls completed',
      scoreTitle: 'AI Visibility Score',
      scoreLong: (c: number | string) => `A weighted measure of how visible you are in AI recommendations. Confidence ${c}% — based on how much data backed this audit.`,
      breaksDown: 'How it breaks down', weight: 'weight', breakdownNA: 'Breakdown not available.',
      mentionsTitle: 'AI Mentions — by model',
      mentionsSub: (c: number) => `How often each assistant named you across the prompts we tested. ${c} of 4 models mention you.`,
      mentionOne: 'mention', mentionMany: 'mentions', avgPos: 'avg pos',
      competitorsTitle: 'Competitors recommended by AI',
      competitorsSub: 'Restaurants the assistants named, by how many times they appeared.',
      noCompetitors: 'No competitors were extracted from this audit.',
      recsEmpty: 'Recommendations appear here once generated for this audit.',
      doFirst: 'Do first', doNext: 'Do next', optional: 'Optional', confidence: 'confidence', impact: 'impact', effort: 'effort',
      websiteTitle: 'Website signals for AI',
      websiteSub: 'What AI crawlers can read on your site — the building blocks of being understood and recommended.',
      noWebsite: 'No website audit available.',
      sig: { schema: 'Restaurant schema (Schema.org)', menu: 'Crawlable menu', hours: 'Opening hours', reservation: 'Reservation link', faq: 'FAQ content', reviews: 'Review signals', location: 'Clear location', social: 'Social links' },
      metaTitle: 'Meta title', openFull: 'Open full report & recommendations',
    },
  },
  nl: {
    login: {
      title: 'Log in op je dashboard',
      sub: 'Vul je e-mailadres in en we sturen je een veilige inloglink — geen wachtwoord nodig.',
      email: 'E-mail', placeholder: 'jij@restaurant.nl', send: 'Stuur me een inloglink',
      sentTitle: 'Check je e-mail',
      sentBody: (e: string) => `We hebben een inloglink naar ${e} gestuurd. Hij werkt één keer en verloopt na 30 minuten.`,
      errExpired: 'Die link is verlopen of al gebruikt. Vul je e-mailadres in voor een nieuwe.',
      errConfig: 'Inloggen is tijdelijk niet beschikbaar. Probeer het later opnieuw.',
      errGeneric: 'Er ging iets mis', errSend: 'Kon de link niet versturen',
    },
    list: {
      title: 'Jouw restaurants', sub: 'Open een restaurant om het AI-zichtbaarheidsdashboard te zien.',
      emptyTitle: 'Nog geen restaurants gekoppeld',
      emptyBody: 'We koppelen dashboards aan het e-mailadres waarmee je audit is aangevraagd. Als je audit nog loopt of je een ander adres gebruikte, verschijnt het mogelijk nog niet. Start een gratis check op de homepage, of beantwoord je auditmail dan koppelen we het.',
      startCheck: 'Start een gratis check', logout: 'Uitloggen',
      auditedOn: (d: string) => `geaudit ${d}`, notAudited: 'nog niet geaudit',
      plan: { free: 'Gratis', audit: 'Audit', implementation: 'Implementatie' } as Record<string, string>,
    },
    detail: {
      allRestaurants: 'Alle restaurants', backOffice: 'Terug naar backoffice',
      adminPreview: 'Adminvoorbeeld — dit is precies wat de klant ziet.', adminPreviewShort: 'Adminvoorbeeld',
    },
    dash: {
      nav: ['Overzicht', 'AI-zichtbaarheidsscore', 'AI-vermeldingen', 'Concurrenten', 'Aanbevelingen', 'Website-audit', 'Trends (Bèta)'],
      fullReport: 'Volledig rapport & PDF',
      preparingTitle: 'Je audit wordt voorbereid',
      preparingBody: 'Zodra je AI-zichtbaarheidsaudit klaar is, verschijnen je score, concurrenten en aanbevelingen hier.',
      bandGood: 'Goed', bandFair: 'Redelijk', bandWork: 'Aandacht nodig',
      scoreOverviewBody: 'Hoe zichtbaar je vandaag bent in AI-aanbevelingen.',
      mentioned: 'Genoemd door AI',
      mentionedBody: (p: number, c: number) => `Je verschijnt in ${p}% van de geteste AI-antwoorden. ${c} van de 4 modellen noemen je.`,
      topCompetitors: 'Top concurrenten', noneExtracted: 'Geen gevonden.',
      overTime: 'Zichtbaarheid over tijd',
      overTimeEmpty: 'Je zichtbaarheid over tijd verschijnt hier naarmate er meer audits draaien. Maandelijkse monitoring komt eraan.',
      keyInsight: 'Belangrijkste inzicht', reliability: 'Betrouwbaarheid', relHigh: 'Hoog', relMed: 'Gemiddeld', relLow: 'Laag',
      relCaption: 'Hoeveel AI-calls voltooid zijn',
      scoreTitle: 'AI-zichtbaarheidsscore',
      scoreLong: (c: number | string) => `Een gewogen maat voor hoe zichtbaar je bent in AI-aanbevelingen. Betrouwbaarheid ${c}% — op basis van hoeveel data deze audit onderbouwde.`,
      breaksDown: 'Hoe het is opgebouwd', weight: 'weging', breakdownNA: 'Opbouw niet beschikbaar.',
      mentionsTitle: 'AI-vermeldingen — per model',
      mentionsSub: (c: number) => `Hoe vaak elke assistent je noemde over de geteste prompts. ${c} van de 4 modellen noemen je.`,
      mentionOne: 'vermelding', mentionMany: 'vermeldingen', avgPos: 'gem. positie',
      competitorsTitle: 'Concurrenten die AI aanbeveelt',
      competitorsSub: 'Restaurants die de assistenten noemden, op aantal keer dat ze verschenen.',
      noCompetitors: 'Er zijn geen concurrenten uit deze audit gehaald.',
      recsEmpty: 'Aanbevelingen verschijnen hier zodra ze voor deze audit zijn gegenereerd.',
      doFirst: 'Eerst doen', doNext: 'Daarna', optional: 'Optioneel', confidence: 'betrouwbaarheid', impact: 'impact', effort: 'inspanning',
      websiteTitle: 'Websitesignalen voor AI',
      websiteSub: 'Wat AI-crawlers op je site kunnen lezen — de bouwstenen om begrepen en aanbevolen te worden.',
      noWebsite: 'Geen website-audit beschikbaar.',
      sig: { schema: 'Restaurant-schema (Schema.org)', menu: 'Crawlbaar menu', hours: 'Openingstijden', reservation: 'Reserveringslink', faq: 'FAQ-inhoud', reviews: 'Reviewsignalen', location: 'Duidelijke locatie', social: 'Social links' },
      metaTitle: 'Meta-titel', openFull: 'Open volledig rapport & aanbevelingen',
    },
  },
} satisfies Record<Language, unknown>
